#!/bin/bash

source .env
python3 -m code.bird_label \
   --conf-threshold 0.6 --no-bird 0.2 \
   --data-dir ./data \
   --output-dir ./output \
   --approach vllm \
   --vllm-url http://darwin:8000/v1 \
   --batch-size 16 \
   --model /data/models/Qwen3-VL-132B-Instruct

   #--model "Qwen/Qwen3-VL-32B-Instruct-FP8"
