#!/bin/bash

python -m vllm.entrypoints.openai.api_server \
  --model cyankiwi/Qwen3.5-122B-A10B-AWQ-4bit \
  --tensor-parallel-size 2 \
  --max-model-len 65536 \
  --gpu-memory-utilization 0.95 \
  --enforce-eager

  python -m vllm.entrypoints.openai.api_server \
  --model cyankiwi/Qwen3.5-122B-A10B-AWQ-4bit \
  --tensor-parallel-size 2 \
  --dtype half \
  --port 8080 \
  --max-model-len 131070 \
  --gpu-memory-utilization 0.95 \
  --enforce-eager \
  --enable-auto-tool-choice \
  --tool-call-parser hermes \
   "$@"
