#!/bin/bash

source .env
python3 -m code.bird_label \
   --conf-threshold 0.6 --no-bird 0.2 \
   --data-dir ./data \
   --output-dir ./output \
   --approach llamac.pp \
   --llama-url http://darwin:8080/v1 