#!/bin/bash

#source .env
python3 -m code.bird_label \
   --conf-threshold 0.7 --no-bird 0.2 \
   --data-dir ./data \
   --output-dir ./output \
   --approach llama.cpp \
   --llama-url http://darwin:8080/v1 