#!/usr/bin/env python3
"""Check a generated report for anything that identifies the collection.

The gate between `local/` and `project/reports/`. A report is generated into
`local/`, which is gitignored wholesale; copying one into the tracked tree is a
deliberate act, and this is the check that act is supposed to survive.

**It reports; it never edits and never copies.** `audit_` means read-only here.
The intended use is as a condition, so a failing check stops the copy:

    python3 -m tools.audit_report_safety local/reports/embed_quality_report.md \\
        && cp local/reports/embed_quality_report.md project/reports/

Exit status is 0 when nothing was found, 1 when something was, 2 on a usage
error -- so it composes with `&&` and with CI.

**What it looks for, and why each one is on the list.** Every item here is
something this project has actually leaked or come close to leaking; the list
is the 2026-08-12 cleanup written down. A secret scanner finds none of them,
which is the point -- gitleaks came back clean on a repository that was
carrying five thousand GPS fixes.

- **trip folder names** -- `2019-08-27 Greenwich & St Paul Church`. Place and
  date together, and the single worst offender: scrubbing EXIF while leaving
  these would have been tidying the wrong thing.
- **image keys and paths** -- `Photos-19/<trip>/_D8S0025.jpg` carries the trip
  name with it, so a key is a place name with extra steps.
- **GPS** -- both the decimal-minutes form Lightroom writes and plain decimal
  pairs. 5,491 sidecars carried these at roughly metre precision.
- **camera serial numbers** -- a serial links a photo to every other photo from
  that body, anywhere on the internet. 90 of 103 sample sidecars had one.
- **the photographer's name** -- taken from `git config user.name` rather than
  hardcoded, so this stays useful for anyone else running it.
- **home directory paths** -- `/home/<user>/...` leaks a username, and absolute
  paths get pasted into reports without anyone thinking about it.
- **CJK text** -- trip folders and Chinese species names are both Chinese, so
  any CJK in a report is worth a human glance.
- **species names** -- the subtle one, and specific to this project. A species
  list sketches a travel history on its own: a black-necked crane and an
  American white pelican in one collection say a good deal about where the
  photographer has been. Checked against the actual label vocabulary in
  `data/label/`, so it flags the birds *this* library contains rather than
  guessing at what a bird name looks like.

A hit is not a verdict. `--anonymise` output from `audit_embed_quality.py` is
meant to pass; the same report with names is meant to fail, and failing is it
working. Read the findings and decide.
"""

import argparse
import csv
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.environ.get("PROJECT_ROOT")
                or str(Path(__file__).resolve().parents[1]))

from code.lib.config import PROJECT_ROOT, data_dir  # noqa: E402

# A trip folder is `YYYY-MM-DD <place>`; the date alone is not interesting, the
# date followed by a *name* is. Also catches the `2021-05-07~08 <place>` form.
#
# The token after the date must look like a place -- capitalised, or CJK -- and
# not like English prose. Every document in this repository dates its own
# paragraphs ("Raised 2026-08-21 by Miles", "Settled 2026-08-12, after..."), and
# matching those made the check fire on all of them, which is how a checker
# stops being read. A lowercase place name would now be missed; that is the
# accepted cost of the tool being trusted at all, and CJK names are caught by
# their own pattern regardless.
TRIP_RE = re.compile(r"\b(?:19|20)\d{2}-\d{2}-\d{2}(?:[~-]\d{2})?\s+"
                     r"(?=[A-Z\u4e00-\u9fff])\S+")
KEY_RE = re.compile(r"\bPhotos-\d{2}\b|\b\w[\w-]*\.(?:jpg|jpeg|xmp|nef|arw|cr3|dng)\b",
                    re.IGNORECASE)
# Lightroom's degrees + decimal-minutes, and a plain decimal pair.
GPS_RE = re.compile(r"\b\d{1,3},\d{1,2}\.\d+[NSEW]\b"
                    r"|\bGPS(?:Latitude|Longitude)\b"
                    r"|\b-?\d{1,3}\.\d{4,}\s*,\s*-?\d{1,3}\.\d{4,}\b")
SERIAL_RE = re.compile(r"\b(?:BodySerialNumber|SerialNumber|serial)\b\W{0,3}([\w-]{4,})",
                       re.IGNORECASE)
HOME_RE = re.compile(r"/home/[^/\s`\"']+|/Users/[^/\s`\"']+")
CJK_RE = re.compile(r"[一-鿿]+")

# Lines this tool's own findings would otherwise trip over, and the documented
# examples inside a report explaining what it does not contain.
SKIP_PREFIXES = ("Generated by ", "No timestamp:")


def git_user() -> str | None:
    try:
        name = subprocess.check_output(["git", "config", "user.name"],
                                       text=True, cwd=PROJECT_ROOT).strip()
        return name or None
    except Exception:
        return None


def species_vocabulary() -> set[str]:
    """Every species this library's labels mention, lowercased.

    Read from the curated label CSV rather than guessed at, so the check is
    about *this* collection. Multi-word names only: a one-word species like
    `smew` collides with ordinary prose, and the cost of missing it is far lower
    than a checker nobody trusts because it cries wolf.

    Bird rows only, for the same reason. The CSV also holds scenery and people
    labels, which are free-text descriptions -- "traditional chinese garden with
    pavilion and trees" -- and feeding those in would make ordinary English
    prose match. The never-demote rule applies: a row the library kept as a bird
    counts as one whatever this run said.
    """
    csv_path = data_dir() / "label" / "bird_identification_output.csv"
    if not csv_path.is_file():
        return set()
    names = set()
    with open(csv_path, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            if "bird" not in ((row.get("category") or "").strip().lower(),
                              (row.get("prior_category") or "").strip().lower()):
                continue
            for column in ("label", "prior_label"):
                raw = (row.get(column) or "").strip().lower()
                # prior_label is `;`-joined, so each entry is handled on its own;
                # splitting a single-entry value is a no-op.
                for part in raw.split(";"):
                    text = part.strip()
                    # `py-cn-en(NN%)`: take the english segment.
                    m = re.match(r"^[^-]+-[^-]+-(.+?)\(\d+%\)$", text)
                    if m:
                        text = m.group(1)
                    # An early free-text label keeps its suffix through the
                    # above, having no py-cn-en shape to match.
                    text = re.sub(r"\(\d+%\)$", "", text).strip()
                    if " " in text and 3 < len(text) < 60:
                        names.add(text)
    return names


def check(path: Path, vocabulary: set[str], user: str | None):
    """[(line number, kind, evidence)] for one file."""
    findings = []
    species_seen = set()
    for n, line in enumerate(path.read_text(encoding="utf-8", errors="replace")
                             .splitlines(), 1):
        if any(line.startswith(p) for p in SKIP_PREFIXES):
            continue
        low = line.lower()
        for kind, pattern in (("trip folder name", TRIP_RE),
                              ("image key or path", KEY_RE),
                              ("GPS", GPS_RE),
                              ("camera serial", SERIAL_RE),
                              ("home directory path", HOME_RE),
                              ("CJK text", CJK_RE)):
            m = pattern.search(line)
            if m:
                findings.append((n, kind, m.group(0).strip()))
        if user and user.lower() in low:
            findings.append((n, "photographer's name", user))
        for name in vocabulary:
            if name in low:
                findings.append((n, "species name", name))
                species_seen.add(name)
                break        # one finding per line is enough to fail it
    return findings, species_seen


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="+", type=Path, help="files to check")
    ap.add_argument("--quiet", action="store_true",
                    help="exit status only, for use as a condition")
    ap.add_argument("--max-per-kind", type=int, default=5,
                    help="findings of each kind to show per file (default 5)")
    args = ap.parse_args()

    for path in args.paths:
        if not path.is_file():
            sys.exit(f"error: {path} is not a file")

    vocabulary = species_vocabulary()
    user = git_user()
    if not args.quiet and not vocabulary:
        print("note: no label CSV found, so species names are not checked",
              file=sys.stderr)

    total = 0
    for path in args.paths:
        findings, species_seen = check(path, vocabulary, user)
        total += len(findings)
        if args.quiet:
            continue
        if not findings:
            print(f"OK   {path}: nothing identifying found")
            continue
        kinds: dict[str, list] = {}
        for n, kind, evidence in findings:
            kinds.setdefault(kind, []).append((n, evidence))
        print(f"FAIL {path}: {len(findings)} finding(s) across {len(kinds)} kind(s)")
        for kind, hits in sorted(kinds.items()):
            extra = f" (+{len(hits) - args.max_per_kind} more)" \
                if len(hits) > args.max_per_kind else ""
            print(f"  {kind}: {len(hits)}{extra}")
            for n, evidence in hits[:args.max_per_kind]:
                print(f"    line {n}: {evidence}")
        if species_seen:
            print(f"    ({len(species_seen)} distinct species named -- a species list "
                  f"sketches a travel history on its own)")

    if total and not args.quiet:
        print("\nNothing was changed. Decide what to do, then copy by hand if it is "
              "safe; `--anonymise` on a report writer is usually the fix.")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
